export const authMutationsTypes = {
  REGISTER_START: 'auth/REGISTER_START',
  REGISTER_SUCCESS: 'auth/REGISTER_SUCCESS',
  REGISTER_FAILURE: 'auth/REGISTER_FAILURE',

  LOGIN_START: 'auth/LOGIN_START',
  LOGIN_SUCCESS: 'auth/LOGIN_SUCCESS',
  LOGIN_FAILURE: 'auth/LOGIN_FAILURE',

  GET_CURRENT_USER_START: 'auth/GET_CURRENT_USER_START',
  GET_CURRENT_USER_SUCCESS: 'auth/GET_CURRENT_USER_SUCCESS',
  GET_CURRENT_USER_FAILURE: 'auth/GET_CURRENT_USER_FAILURE',

  LOGOUT: 'auth/LOGOUT',
};

export const authActionsTypes = {
  SIGN_UP: 'auth/SIGN_UP',
  SIGN_IN: 'auth/SIGN_IN',
  LOGOUT: 'auth/LOGOUT',
  GET_CURRENT_USER: 'auth/GET_CURRENT_USER',
};
